version: '3.5'

services:
  db:
    container_name: postgres-test
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-test-data:
